// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_summaries.sql

package db

import (
	"context"
	"database/sql"
)

const createSessionSummary = `-- name: CreateSessionSummary :one
INSERT INTO session_summaries (
    id,
    session_id,
    summary_text,
    embedding,
    key_topics,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, strftime('%s', 'now')
)
RETURNING id, session_id, summary_text, embedding, key_topics, created_at
`

type CreateSessionSummaryParams struct {
	ID          string         `json:"id"`
	SessionID   string         `json:"session_id"`
	SummaryText string         `json:"summary_text"`
	Embedding   []byte         `json:"embedding"`
	KeyTopics   sql.NullString `json:"key_topics"`
}

func (q *Queries) CreateSessionSummary(ctx context.Context, arg CreateSessionSummaryParams) (SessionSummary, error) {
	row := q.queryRow(ctx, q.createSessionSummaryStmt, createSessionSummary,
		arg.ID,
		arg.SessionID,
		arg.SummaryText,
		arg.Embedding,
		arg.KeyTopics,
	)
	var i SessionSummary
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SummaryText,
		&i.Embedding,
		&i.KeyTopics,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionSummariesBySessionID = `-- name: DeleteSessionSummariesBySessionID :exec
DELETE FROM session_summaries
WHERE session_id = ?
`

func (q *Queries) DeleteSessionSummariesBySessionID(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionSummariesBySessionIDStmt, deleteSessionSummariesBySessionID, sessionID)
	return err
}

const deleteSessionSummary = `-- name: DeleteSessionSummary :exec
DELETE FROM session_summaries
WHERE id = ?
`

func (q *Queries) DeleteSessionSummary(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSessionSummaryStmt, deleteSessionSummary, id)
	return err
}

const getSessionSummary = `-- name: GetSessionSummary :one
SELECT id, session_id, summary_text, embedding, key_topics, created_at
FROM session_summaries
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionSummary(ctx context.Context, id string) (SessionSummary, error) {
	row := q.queryRow(ctx, q.getSessionSummaryStmt, getSessionSummary, id)
	var i SessionSummary
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SummaryText,
		&i.Embedding,
		&i.KeyTopics,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionSummaryBySessionID = `-- name: GetSessionSummaryBySessionID :one
SELECT id, session_id, summary_text, embedding, key_topics, created_at
FROM session_summaries
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSessionSummaryBySessionID(ctx context.Context, sessionID string) (SessionSummary, error) {
	row := q.queryRow(ctx, q.getSessionSummaryBySessionIDStmt, getSessionSummaryBySessionID, sessionID)
	var i SessionSummary
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SummaryText,
		&i.Embedding,
		&i.KeyTopics,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionSummaries = `-- name: ListSessionSummaries :many
SELECT id, session_id, summary_text, embedding, key_topics, created_at
FROM session_summaries
ORDER BY created_at DESC
`

func (q *Queries) ListSessionSummaries(ctx context.Context) ([]SessionSummary, error) {
	rows, err := q.query(ctx, q.listSessionSummariesStmt, listSessionSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionSummary{}
	for rows.Next() {
		var i SessionSummary
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SummaryText,
			&i.Embedding,
			&i.KeyTopics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionSummariesWithEmbeddings = `-- name: ListSessionSummariesWithEmbeddings :many
SELECT id, session_id, summary_text, embedding, key_topics, created_at
FROM session_summaries
WHERE embedding IS NOT NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSessionSummariesWithEmbeddings(ctx context.Context) ([]SessionSummary, error) {
	rows, err := q.query(ctx, q.listSessionSummariesWithEmbeddingsStmt, listSessionSummariesWithEmbeddings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionSummary{}
	for rows.Next() {
		var i SessionSummary
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SummaryText,
			&i.Embedding,
			&i.KeyTopics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionSummaryEmbedding = `-- name: UpdateSessionSummaryEmbedding :exec
UPDATE session_summaries
SET embedding = ?
WHERE id = ?
`

type UpdateSessionSummaryEmbeddingParams struct {
	Embedding []byte `json:"embedding"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateSessionSummaryEmbedding(ctx context.Context, arg UpdateSessionSummaryEmbeddingParams) error {
	_, err := q.exec(ctx, q.updateSessionSummaryEmbeddingStmt, updateSessionSummaryEmbedding, arg.Embedding, arg.ID)
	return err
}
