// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
	"database/sql"
)

const getAverageResponseTime = `-- name: GetAverageResponseTime :one
SELECT
    CAST(COALESCE(AVG(finished_at - created_at), 0) AS INTEGER) as avg_response_seconds
FROM messages
WHERE role = 'assistant'
  AND finished_at IS NOT NULL
  AND finished_at > created_at
`

func (q *Queries) GetAverageResponseTime(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getAverageResponseTimeStmt, getAverageResponseTime)
	var avg_response_seconds int64
	err := row.Scan(&avg_response_seconds)
	return avg_response_seconds, err
}

const getHeatmapDateRange = `-- name: GetHeatmapDateRange :one
SELECT
    date(MIN(created_at), 'unixepoch', 'localtime') as first_day,
    date(MAX(created_at), 'unixepoch', 'localtime') as last_day,
    CAST(julianday(date(MAX(created_at), 'unixepoch', 'localtime')) - julianday(date(MIN(created_at), 'unixepoch', 'localtime')) + 1 AS INTEGER) as total_days
FROM sessions
WHERE parent_session_id IS NULL
`

type GetHeatmapDateRangeRow struct {
	FirstDay  interface{} `json:"first_day"`
	LastDay   interface{} `json:"last_day"`
	TotalDays int64       `json:"total_days"`
}

func (q *Queries) GetHeatmapDateRange(ctx context.Context) (GetHeatmapDateRangeRow, error) {
	row := q.queryRow(ctx, q.getHeatmapDateRangeStmt, getHeatmapDateRange)
	var i GetHeatmapDateRangeRow
	err := row.Scan(&i.FirstDay, &i.LastDay, &i.TotalDays)
	return i, err
}

const getHourDayTokenHeatmap = `-- name: GetHourDayTokenHeatmap :many
SELECT
    CAST(strftime('%w', created_at, 'unixepoch', 'localtime') AS INTEGER) as day_of_week,
    CAST(strftime('%H', created_at, 'unixepoch', 'localtime') AS INTEGER) as hour,
    COALESCE(SUM(prompt_tokens + completion_tokens), 0) as total_tokens,
    COALESCE(SUM(input_tokens + completion_tokens), 0) as total_tokens_excl_cache
FROM sessions
WHERE parent_session_id IS NULL
GROUP BY day_of_week, hour
ORDER BY day_of_week, hour
`

type GetHourDayTokenHeatmapRow struct {
	DayOfWeek            int64       `json:"day_of_week"`
	Hour                 int64       `json:"hour"`
	TotalTokens          interface{} `json:"total_tokens"`
	TotalTokensExclCache interface{} `json:"total_tokens_excl_cache"`
}

func (q *Queries) GetHourDayTokenHeatmap(ctx context.Context) ([]GetHourDayTokenHeatmapRow, error) {
	rows, err := q.query(ctx, q.getHourDayTokenHeatmapStmt, getHourDayTokenHeatmap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHourDayTokenHeatmapRow{}
	for rows.Next() {
		var i GetHourDayTokenHeatmapRow
		if err := rows.Scan(
			&i.DayOfWeek,
			&i.Hour,
			&i.TotalTokens,
			&i.TotalTokensExclCache,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT
    date(created_at, 'unixepoch') as day,
    COUNT(*) as session_count,
    SUM(prompt_tokens + completion_tokens) as total_tokens,
    SUM(cost) as cost
FROM sessions
WHERE parent_session_id IS NULL
  AND created_at >= strftime('%s', 'now', '-30 days')
GROUP BY date(created_at, 'unixepoch')
ORDER BY day ASC
`

type GetRecentActivityRow struct {
	Day          interface{}     `json:"day"`
	SessionCount int64           `json:"session_count"`
	TotalTokens  sql.NullFloat64 `json:"total_tokens"`
	Cost         sql.NullFloat64 `json:"cost"`
}

func (q *Queries) GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error) {
	rows, err := q.query(ctx, q.getRecentActivityStmt, getRecentActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentActivityRow{}
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.Day,
			&i.SessionCount,
			&i.TotalTokens,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToolUsage = `-- name: GetToolUsage :many
SELECT
    json_extract(value, '$.data.name') as tool_name,
    COUNT(*) as call_count
FROM messages, json_each(parts)
WHERE json_extract(value, '$.type') = 'tool_call'
  AND json_extract(value, '$.data.name') IS NOT NULL
GROUP BY tool_name
ORDER BY call_count DESC
`

type GetToolUsageRow struct {
	ToolName  interface{} `json:"tool_name"`
	CallCount int64       `json:"call_count"`
}

func (q *Queries) GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error) {
	rows, err := q.query(ctx, q.getToolUsageStmt, getToolUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetToolUsageRow{}
	for rows.Next() {
		var i GetToolUsageRow
		if err := rows.Scan(&i.ToolName, &i.CallCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToolUsageWithTokens = `-- name: GetToolUsageWithTokens :many
SELECT
    tool_name,
    call_count,
    total_chars,
    -- Estimate tokens as chars/4 (rough approximation)
    CAST(total_chars / 4 AS INTEGER) as estimated_tokens
FROM (
    SELECT
        json_extract(value, '$.data.name') as tool_name,
        COUNT(*) as call_count,
        COALESCE(SUM(LENGTH(json_extract(value, '$.data.content'))), 0) as total_chars
    FROM messages, json_each(parts)
    WHERE json_extract(value, '$.type') = 'tool_result'
      AND json_extract(value, '$.data.name') IS NOT NULL
    GROUP BY tool_name
)
ORDER BY estimated_tokens DESC
`

type GetToolUsageWithTokensRow struct {
	ToolName        interface{} `json:"tool_name"`
	CallCount       int64       `json:"call_count"`
	TotalChars      interface{} `json:"total_chars"`
	EstimatedTokens int64       `json:"estimated_tokens"`
}

func (q *Queries) GetToolUsageWithTokens(ctx context.Context) ([]GetToolUsageWithTokensRow, error) {
	rows, err := q.query(ctx, q.getToolUsageWithTokensStmt, getToolUsageWithTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetToolUsageWithTokensRow{}
	for rows.Next() {
		var i GetToolUsageWithTokensRow
		if err := rows.Scan(
			&i.ToolName,
			&i.CallCount,
			&i.TotalChars,
			&i.EstimatedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalStats = `-- name: GetTotalStats :one
SELECT
    COUNT(*) as total_sessions,
    COALESCE(SUM(prompt_tokens), 0) as total_prompt_tokens,
    COALESCE(SUM(completion_tokens), 0) as total_completion_tokens,
    COALESCE(SUM(input_tokens), 0) as total_input_tokens,
    COALESCE(SUM(cache_read_tokens), 0) as total_cache_read_tokens,
    COALESCE(SUM(cache_write_tokens), 0) as total_cache_write_tokens,
    COALESCE(SUM(cost), 0) as total_cost,
    COALESCE(SUM(message_count), 0) as total_messages,
    COALESCE(AVG(prompt_tokens + completion_tokens), 0) as avg_tokens_per_session,
    COALESCE(AVG(message_count), 0) as avg_messages_per_session
FROM sessions
WHERE parent_session_id IS NULL
`

type GetTotalStatsRow struct {
	TotalSessions         int64       `json:"total_sessions"`
	TotalPromptTokens     interface{} `json:"total_prompt_tokens"`
	TotalCompletionTokens interface{} `json:"total_completion_tokens"`
	TotalInputTokens      interface{} `json:"total_input_tokens"`
	TotalCacheReadTokens  interface{} `json:"total_cache_read_tokens"`
	TotalCacheWriteTokens interface{} `json:"total_cache_write_tokens"`
	TotalCost             interface{} `json:"total_cost"`
	TotalMessages         interface{} `json:"total_messages"`
	AvgTokensPerSession   interface{} `json:"avg_tokens_per_session"`
	AvgMessagesPerSession interface{} `json:"avg_messages_per_session"`
}

func (q *Queries) GetTotalStats(ctx context.Context) (GetTotalStatsRow, error) {
	row := q.queryRow(ctx, q.getTotalStatsStmt, getTotalStats)
	var i GetTotalStatsRow
	err := row.Scan(
		&i.TotalSessions,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.TotalInputTokens,
		&i.TotalCacheReadTokens,
		&i.TotalCacheWriteTokens,
		&i.TotalCost,
		&i.TotalMessages,
		&i.AvgTokensPerSession,
		&i.AvgMessagesPerSession,
	)
	return i, err
}

const getUsageByDay = `-- name: GetUsageByDay :many
SELECT
    date(created_at, 'unixepoch') as day,
    SUM(prompt_tokens) as prompt_tokens,
    SUM(completion_tokens) as completion_tokens,
    SUM(input_tokens) as input_tokens,
    SUM(cache_read_tokens) as cache_read_tokens,
    SUM(cache_write_tokens) as cache_write_tokens,
    SUM(cost) as cost,
    COUNT(*) as session_count
FROM sessions
WHERE parent_session_id IS NULL
GROUP BY date(created_at, 'unixepoch')
ORDER BY day DESC
`

type GetUsageByDayRow struct {
	Day              interface{}     `json:"day"`
	PromptTokens     sql.NullFloat64 `json:"prompt_tokens"`
	CompletionTokens sql.NullFloat64 `json:"completion_tokens"`
	InputTokens      sql.NullFloat64 `json:"input_tokens"`
	CacheReadTokens  sql.NullFloat64 `json:"cache_read_tokens"`
	CacheWriteTokens sql.NullFloat64 `json:"cache_write_tokens"`
	Cost             sql.NullFloat64 `json:"cost"`
	SessionCount     int64           `json:"session_count"`
}

func (q *Queries) GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error) {
	rows, err := q.query(ctx, q.getUsageByDayStmt, getUsageByDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageByDayRow{}
	for rows.Next() {
		var i GetUsageByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.Cost,
			&i.SessionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageByDayOfWeek = `-- name: GetUsageByDayOfWeek :many
SELECT
    CAST(strftime('%w', created_at, 'unixepoch') AS INTEGER) as day_of_week,
    COUNT(*) as session_count,
    SUM(prompt_tokens) as prompt_tokens,
    SUM(completion_tokens) as completion_tokens,
    SUM(input_tokens) as input_tokens,
    SUM(cache_read_tokens) as cache_read_tokens,
    SUM(cache_write_tokens) as cache_write_tokens
FROM sessions
WHERE parent_session_id IS NULL
GROUP BY day_of_week
ORDER BY day_of_week
`

type GetUsageByDayOfWeekRow struct {
	DayOfWeek        int64           `json:"day_of_week"`
	SessionCount     int64           `json:"session_count"`
	PromptTokens     sql.NullFloat64 `json:"prompt_tokens"`
	CompletionTokens sql.NullFloat64 `json:"completion_tokens"`
	InputTokens      sql.NullFloat64 `json:"input_tokens"`
	CacheReadTokens  sql.NullFloat64 `json:"cache_read_tokens"`
	CacheWriteTokens sql.NullFloat64 `json:"cache_write_tokens"`
}

func (q *Queries) GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error) {
	rows, err := q.query(ctx, q.getUsageByDayOfWeekStmt, getUsageByDayOfWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageByDayOfWeekRow{}
	for rows.Next() {
		var i GetUsageByDayOfWeekRow
		if err := rows.Scan(
			&i.DayOfWeek,
			&i.SessionCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageByHour = `-- name: GetUsageByHour :many
SELECT
    CAST(strftime('%H', created_at, 'unixepoch', 'localtime') AS INTEGER) as hour,
    COUNT(*) as session_count
FROM sessions
WHERE parent_session_id IS NULL
GROUP BY hour
ORDER BY hour
`

type GetUsageByHourRow struct {
	Hour         int64 `json:"hour"`
	SessionCount int64 `json:"session_count"`
}

func (q *Queries) GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error) {
	rows, err := q.query(ctx, q.getUsageByHourStmt, getUsageByHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageByHourRow{}
	for rows.Next() {
		var i GetUsageByHourRow
		if err := rows.Scan(&i.Hour, &i.SessionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageByModel = `-- name: GetUsageByModel :many
SELECT
    COALESCE(model, 'unknown') as model,
    COALESCE(provider, 'unknown') as provider,
    COUNT(*) as message_count
FROM messages
WHERE role = 'assistant'
GROUP BY model, provider
ORDER BY message_count DESC
`

type GetUsageByModelRow struct {
	Model        string `json:"model"`
	Provider     string `json:"provider"`
	MessageCount int64  `json:"message_count"`
}

func (q *Queries) GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error) {
	rows, err := q.query(ctx, q.getUsageByModelStmt, getUsageByModel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageByModelRow{}
	for rows.Next() {
		var i GetUsageByModelRow
		if err := rows.Scan(&i.Model, &i.Provider, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
