// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tool_metrics.sql

package db

import (
	"context"
	"database/sql"
)

const deleteSessionToolMetrics = `-- name: DeleteSessionToolMetrics :exec
DELETE FROM tool_metrics WHERE session_id = ?
`

func (q *Queries) DeleteSessionToolMetrics(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionToolMetricsStmt, deleteSessionToolMetrics, sessionID)
	return err
}

const getAllToolMetricsSummary = `-- name: GetAllToolMetricsSummary :many
SELECT
    tool_name,
    COUNT(*) as call_count,
    AVG(duration_ms) as avg_duration_ms,
    MIN(duration_ms) as min_duration_ms,
    MAX(duration_ms) as max_duration_ms,
    SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) as success_count,
    SUM(CASE WHEN success = 0 THEN 1 ELSE 0 END) as failure_count
FROM tool_metrics
GROUP BY tool_name
ORDER BY call_count DESC
`

type GetAllToolMetricsSummaryRow struct {
	ToolName      string          `json:"tool_name"`
	CallCount     int64           `json:"call_count"`
	AvgDurationMs sql.NullFloat64 `json:"avg_duration_ms"`
	MinDurationMs interface{}     `json:"min_duration_ms"`
	MaxDurationMs interface{}     `json:"max_duration_ms"`
	SuccessCount  sql.NullFloat64 `json:"success_count"`
	FailureCount  sql.NullFloat64 `json:"failure_count"`
}

func (q *Queries) GetAllToolMetricsSummary(ctx context.Context) ([]GetAllToolMetricsSummaryRow, error) {
	rows, err := q.query(ctx, q.getAllToolMetricsSummaryStmt, getAllToolMetricsSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllToolMetricsSummaryRow{}
	for rows.Next() {
		var i GetAllToolMetricsSummaryRow
		if err := rows.Scan(
			&i.ToolName,
			&i.CallCount,
			&i.AvgDurationMs,
			&i.MinDurationMs,
			&i.MaxDurationMs,
			&i.SuccessCount,
			&i.FailureCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionToolMetrics = `-- name: GetSessionToolMetrics :many
SELECT id, session_id, tool_name, started_at, duration_ms, success, error_message, input_size, output_size FROM tool_metrics
WHERE session_id = ?
ORDER BY started_at DESC
`

func (q *Queries) GetSessionToolMetrics(ctx context.Context, sessionID string) ([]ToolMetric, error) {
	rows, err := q.query(ctx, q.getSessionToolMetricsStmt, getSessionToolMetrics, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolMetric{}
	for rows.Next() {
		var i ToolMetric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ToolName,
			&i.StartedAt,
			&i.DurationMs,
			&i.Success,
			&i.ErrorMessage,
			&i.InputSize,
			&i.OutputSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSlowestTools = `-- name: GetSlowestTools :many
SELECT id, session_id, tool_name, started_at, duration_ms, success, error_message, input_size, output_size FROM tool_metrics
WHERE session_id = ?
ORDER BY duration_ms DESC
LIMIT ?
`

type GetSlowestToolsParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) GetSlowestTools(ctx context.Context, arg GetSlowestToolsParams) ([]ToolMetric, error) {
	rows, err := q.query(ctx, q.getSlowestToolsStmt, getSlowestTools, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolMetric{}
	for rows.Next() {
		var i ToolMetric
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ToolName,
			&i.StartedAt,
			&i.DurationMs,
			&i.Success,
			&i.ErrorMessage,
			&i.InputSize,
			&i.OutputSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToolMetricsSummary = `-- name: GetToolMetricsSummary :many
SELECT
    tool_name,
    COUNT(*) as call_count,
    AVG(duration_ms) as avg_duration_ms,
    MIN(duration_ms) as min_duration_ms,
    MAX(duration_ms) as max_duration_ms,
    SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) as success_count,
    SUM(CASE WHEN success = 0 THEN 1 ELSE 0 END) as failure_count
FROM tool_metrics
WHERE session_id = ?
GROUP BY tool_name
ORDER BY call_count DESC
`

type GetToolMetricsSummaryRow struct {
	ToolName      string          `json:"tool_name"`
	CallCount     int64           `json:"call_count"`
	AvgDurationMs sql.NullFloat64 `json:"avg_duration_ms"`
	MinDurationMs interface{}     `json:"min_duration_ms"`
	MaxDurationMs interface{}     `json:"max_duration_ms"`
	SuccessCount  sql.NullFloat64 `json:"success_count"`
	FailureCount  sql.NullFloat64 `json:"failure_count"`
}

func (q *Queries) GetToolMetricsSummary(ctx context.Context, sessionID string) ([]GetToolMetricsSummaryRow, error) {
	rows, err := q.query(ctx, q.getToolMetricsSummaryStmt, getToolMetricsSummary, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetToolMetricsSummaryRow{}
	for rows.Next() {
		var i GetToolMetricsSummaryRow
		if err := rows.Scan(
			&i.ToolName,
			&i.CallCount,
			&i.AvgDurationMs,
			&i.MinDurationMs,
			&i.MaxDurationMs,
			&i.SuccessCount,
			&i.FailureCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordToolMetric = `-- name: RecordToolMetric :exec
INSERT INTO tool_metrics (
    session_id,
    tool_name,
    started_at,
    duration_ms,
    success,
    error_message,
    input_size,
    output_size
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type RecordToolMetricParams struct {
	SessionID    string         `json:"session_id"`
	ToolName     string         `json:"tool_name"`
	StartedAt    int64          `json:"started_at"`
	DurationMs   int64          `json:"duration_ms"`
	Success      int64          `json:"success"`
	ErrorMessage sql.NullString `json:"error_message"`
	InputSize    sql.NullInt64  `json:"input_size"`
	OutputSize   sql.NullInt64  `json:"output_size"`
}

func (q *Queries) RecordToolMetric(ctx context.Context, arg RecordToolMetricParams) error {
	_, err := q.exec(ctx, q.recordToolMetricStmt, recordToolMetric,
		arg.SessionID,
		arg.ToolName,
		arg.StartedAt,
		arg.DurationMs,
		arg.Success,
		arg.ErrorMessage,
		arg.InputSize,
		arg.OutputSize,
	)
	return err
}
